=== nebula-plugins/gradle-resolution-rules/src/test/resources/valid-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Resolution Rule",
  "description": "validation of resolution rules",
  "type": "object",
  "properties": {
    "align": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "includes": {
            "type": "array"
          },
          "excludes": {
            "type": "array"
          },
          "match": {
            "type": "string"
          },
          "ruleSet": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        },
        "required": [
          "includes",
          "excludes",
          "reason",
          "author",
          "date",
          "group"
        ],
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "deny": {
      "type": "array"
    },
    "exclude": {
      "type": "array"
    },
    "reject": {
      "type": "array"
    },
    "replace": {
      "type": "array"
    },
    "substitute": {
      "type": "array"
    }
  },
  "required": [
    "align",
    "deny",
    "exclude",
    "reject",
    "replace",
    "substitute"
  ],
  "additionalProperties": false
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-spring-integration.json
{
    "align": [
        {
            "name": "align-springframework-integration",
            "group": "org\\.springframework\\.integration",
            "includes": [],
            "excludes": ["spring-integration-(smb|java-dsl|kafka|tuple|cassandra|flow|smpp|splunk|httpinvoker|parent|adapter|samples|aws)"],
            "reason": "Align Spring Integration",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-05-16"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/optional-slf4j-bridge.json
{
    "substitute": [
        {
            "module": "commons-logging:commons-logging",
            "with": "org.slf4j:jcl-over-slf4j:1.7.+",
            "reason": "Subsitute Commons Logging with SLF4J bridge",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-04-28T22:31:14.321Z"
        },
        {
            "module": "log4j:log4j",
            "with": "org.slf4j:log4j-over-slf4j:1.7.+",
            "reason": "Subsitute log4j with SLF4J bridge",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-04-28T22:31:14.321Z"
        }
    ],
    "replace": [],
    "align": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/replace-bouncycastle-with-jdk15.json
{
    "replace": [
        {
            "module": "org.bouncycastle:bcmail-jdk14",
            "with": "org.bouncycastle:bcmail-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk12",
            "with": "org.bouncycastle:bcpg-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk14",
            "with": "org.bouncycastle:bcpg-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk12",
            "with": "org.bouncycastle:bcprov-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk14",
            "with": "org.bouncycastle:bcprov-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-ext-jdk14",
            "with": "org.bouncycastle:bcprov-ext-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctsp-jdk14",
            "with": "org.bouncycastle:bctsp-jdk15",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        }
    ],
    "substitute": [],
    "align": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/replace-bouncycastle-with-jdk15to18.json
{
    "replace": [
        {
            "module": "org.bouncycastle:bcjmail-jdk15on",
            "with": "org.bouncycastle:bcjmail-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcmail-jdk14",
            "with": "org.bouncycastle:bcmail-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcmail-jdk15",
            "with": "org.bouncycastle:bcmail-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcmail-jdk15+",
            "with": "org.bouncycastle:bcmail-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcmail-jdk15on",
            "with": "org.bouncycastle:bcmail-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcmail-jdk16",
            "with": "org.bouncycastle:bcmail-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk12",
            "with": "org.bouncycastle:bcpg-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk14",
            "with": "org.bouncycastle:bcpg-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk15",
            "with": "org.bouncycastle:bcpg-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk15+",
            "with": "org.bouncycastle:bcpg-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk15on",
            "with": "org.bouncycastle:bcpg-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpg-jdk16",
            "with": "org.bouncycastle:bcpg-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpkix-jdk14",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcpkix-jdk15on",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk12",
            "with": "org.bouncycastle:bcprov-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk14",
            "with": "org.bouncycastle:bcprov-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk15",
            "with": "org.bouncycastle:bcprov-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk15+",
            "with": "org.bouncycastle:bcprov-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk15on",
            "with": "org.bouncycastle:bcprov-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk16",
            "with": "org.bouncycastle:bcprov-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-ext-jdk14",
            "with": "org.bouncycastle:bcprov-ext-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-ext-jdk15",
            "with": "org.bouncycastle:bcprov-ext-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-ext-jdk15on",
            "with": "org.bouncycastle:bcprov-ext-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-ext-jdk16",
            "with": "org.bouncycastle:bcprov-ext-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctls-jdk14",
            "with": "org.bouncycastle:bctls-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctls-jdk15on",
            "with": "org.bouncycastle:bctls-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctsp-jdk14",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "bctsp was merged into bcpkix at version 1.47",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctsp-jdk15",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "bctsp was merged into bcpkix at version 1.47",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctsp-jdk15+",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "bctsp was merged into bcpkix at version 1.47",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctsp-jdk15on",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "bctsp was merged into bcpkix at version 1.47",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bctsp-jdk16",
            "with": "org.bouncycastle:bcpkix-jdk15to18",
            "reason": "bctsp was merged into bcpkix at version 1.47",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcutil-jdk14",
            "with": "org.bouncycastle:bcutil-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcutil-jdk15on",
            "with": "org.bouncycastle:bcutil-jdk15to18",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        }
    ],
    "substitute": [],
    "align": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-xbean.json
{
    "align": [
        {
            "name": "align-xbean",
            "group": "org\\.apache\\.xbean",
            "includes": ["xbean-finder-shaded", "xbean-telnet", "xbean-blueprint", "xbean-reflect", "xbean-asm5-shaded", "xbean-naming", "xbean-finder", "xbean-asm-util", "xbean-bundleutils", "xbean-classpath", "xbean-classloader", "maven-xbean-plugin", "xbean-spring", "xbean"],
            "excludes": [],
            "reason": "Align xbean libraries.",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-05-16"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-hibernate-validator.json
{
  "align": [
    {
      "name": "align-hibernate-validator",
      "group": "org\\.hibernate",
      "includes": ["hibernate-validator", "hibernate-validator-.*"],
      "excludes": [],
      "reason": "Align hibernate-validator libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-hibernate-search.json
{
  "align": [
    {
      "name": "align-hibernate-search",
      "group": "org\\.hibernate",
      "includes": ["hibernate-search", "hibernate-search-.*"],
      "excludes": [],
      "reason": "Align hibernate-search libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/replace-bouncycastle-with-jdk14.json
{
    "replace": [
        {
            "module": "org.bouncycastle:bcpg-jdk12",
            "with": "org.bouncycastle:bcpg-jdk14",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        },
        {
            "module": "org.bouncycastle:bcprov-jdk12",
            "with": "org.bouncycastle:bcprov-jdk14",
            "reason": "Ensure that bouncycastle artifacts conflict resolve",
            "author": "Danny Thomas",
            "date": "2026-03-11"
        }
    ],
    "substitute": [],
    "align": [],
    "deny": [],
    "exclude": [],
    "reject": []
}
